<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Bulk Personal Reports</title>
    <style>
        body { font-family: 'Helvetica', 'Arial', sans-serif; font-size: 10px; color: #333; margin: 0; padding: 0; }
        .page-break { page-break-after: always; }
        .header { text-align: center; border-bottom: 2px solid #1a202c; padding-bottom: 10px; margin-bottom: 15px; }
        .header h1 { margin: 0; font-size: 20px; font-weight: bold; color: #1a202c; letter-spacing: 1px; }
        .header p { margin: 2px 0 0 0; color: #4a5568; font-size: 12px; }
        .meta-info { width: 100%; margin-bottom: 15px; border-top: 1px solid #e2e8f0; padding-top: 10px; }
        .meta-info td { vertical-align: top; }
        .meta-title { font-weight: bold; color: #718096; font-size: 9px; text-transform: uppercase; margin-bottom: 3px; }
        .data-table { width: 100%; border-collapse: collapse; margin-bottom: 15px; }
        .data-table th, .data-table td { border: 1px solid #cbd5e0; padding: 6px; text-align: left; }
        .data-table th { background-color: #f7fafc; font-weight: bold; color: #2d3748; text-transform: uppercase; font-size: 9px; }
        .data-table tbody tr:nth-child(even) { background-color: #f8fafc; }
        .text-center { text-align: center; }
        .text-right { text-align: right; }
        .summary-box { width: 100%; margin-bottom: 15px; border-collapse: collapse; }
        .summary-box td { border: 1px solid #cbd5e0; padding: 8px; text-align: center; background-color: #f7fafc; }
        .summary-value { font-size: 14px; font-weight: bold; color: #2b6cb0; margin-top: 3px; }
        .footer { margin-top: 30px; }
        .signature-box { width: 200px; display: inline-block; text-align: center; }
        .signature-line { border-bottom: 1px solid #000; margin-bottom: 5px; height: 30px; }
    </style>
</head>
<body>

@foreach($reports as $index => $reportParams)
    @php
        $type = $reportParams['type'];
        $dateFrom = $reportParams['dateFrom'];
        $dateTo = $reportParams['dateTo'];
        $data = $reportParams['data'];
        $employeeId = $reportParams['employeeId'];
        $employee = $data->first()->employee ?? \App\Models\Employee::find($employeeId);
    @endphp

    <div class="header">
        <h1>{{ strtoupper(\App\Models\Setting::getValue('company_name', 'PROFITIX HRM SYSTEM')) }}</h1>
        <p>Official Attendance & Performance Report (Personal Report)</p>
    </div>

    <table class="meta-info">
        <tr>
            <td width="50%">
                <div class="meta-title">Employee Details:</div>
                <div style="font-size: 14px; font-weight: bold;">{{ $employee->full_name }}</div>
                <div>Code: {{ $employee->employee_code }} | Dept: {{ $employee->department->name ?? '-' }}</div>
            </td>
            <td width="25%">
                <div class="meta-title">Report Period:</div>
                <div style="font-size: 12px; font-weight: bold;">{{ \Carbon\Carbon::parse($dateFrom)->format('d M Y') }} to {{ \Carbon\Carbon::parse($dateTo)->format('d M Y') }}</div>
            </td>
            <td width="25%" class="text-right">
                <div class="meta-title">Generated On:</div>
                <div>{{ now()->format('d M Y, H:i') }}</div>
                <div class="meta-title" style="margin-top: 10px;">Generated By:</div>
                <div>{{ auth()->user()->name }} ({{ strtoupper(auth()->user()->role) }})</div>
            </td>
        </tr>
    </table>

    <table class="summary-box">
        <tr>
            <td>
                <div class="meta-title">Present Days</div>
                <div class="summary-value">{{ $data->whereIn('status', ['present', 'late', 'missing_checkout'])->count() }}</div>
            </td>
            <td>
                <div class="meta-title">Late Days</div>
                <div class="summary-value">{{ $data->where('is_late', true)->count() }}</div>
            </td>
            <td>
                <div class="meta-title">Absent</div>
                <div class="summary-value" style="color: #e53e3e;">{{ $data->where('status', 'absent')->count() }}</div>
            </td>
            <td>
                <div class="meta-title">Leave / Holiday</div>
                <div class="summary-value">{{ $data->whereIn('status', ['leave', 'holiday'])->count() }}</div>
            </td>
            <td>
                <div class="meta-title">Total Work Hours</div>
                <div class="summary-value" style="color: #38a169;">{{ number_format($data->sum('total_hours'), 1) }}h</div>
            </td>
            <td>
                <div class="meta-title">Overtime (OT)</div>
                <div class="summary-value" style="color: #38a169;">+{{ number_format($data->sum('overtime_hours'), 1) }}h</div>
            </td>
        </tr>
    </table>

    <table class="data-table">
        <thead>
            <tr>
                <th>Date</th>
                <th>Shift</th>
                <th>Punch In</th>
                <th>Punch Out</th>
                <th>Work Hrs</th>
                <th>Overtime</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($data as $r)
            <tr>
                <td>{{ $r->summary_date->format('D, d M Y') }}</td>
                <td>{{ $r->shift->name ?? '-' }}</td>
                <td style="color: #38a169;">{{ $r->check_in_time ? date('H:i', strtotime($r->check_in_time)) : '--:--' }}</td>
                <td style="color: #e53e3e;">{{ $r->check_out_time ? date('H:i', strtotime($r->check_out_time)) : '--:--' }}</td>
                <td style="font-weight: bold;">{{ number_format($r->total_hours, 1) }}h</td>
                <td style="color: #3182ce;">@if($r->overtime_hours > 0) +{{ number_format($r->overtime_hours, 1) }}h @else - @endif</td>
                <td>{{ strtoupper(str_replace('_',' ',$r->status)) }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <div class="signature-box">
            <div class="signature-line"></div>
            <div class="meta-title">Employee Signature</div>
        </div>
        <div class="signature-box" style="float: right;">
            <div class="signature-line"></div>
            <div class="meta-title">Authorized By (HR)</div>
        </div>
        <div style="clear: both; margin-top: 40px; text-align: center; font-size: 9px; color: #a0aec0; text-transform: uppercase;">
            --- {{ \App\Models\Setting::getValue('company_name', 'Profitix HRM System') }} | Digitally Generated ---
        </div>
    </div>

    @if(!$loop->last)
        <div class="page-break"></div>
    @endif
@endforeach

</body>
</html>
