<!DOCTYPE html>
<html lang="sw">
<head>
    <meta charset="UTF-8">
    <title>Ripoti ya Mfumo - Profitix HRM</title>
    <style>
        body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 11px; color: #333; margin: 0; padding: 20px; }
        .header { text-align: center; border-bottom: 3px solid #1a202c; padding-bottom: 10px; margin-bottom: 20px; }
        .header h1 { margin: 0; font-size: 24px; text-transform: uppercase; letter-spacing: 1px; color: #1a202c; }
        .header p { margin: 5px 0 0; font-size: 12px; color: #4a5568; }
        .meta-info { width: 100%; margin-bottom: 20px; }
        .meta-info td { padding: 5px; vertical-align: top; }
        .meta-title { font-weight: bold; text-transform: uppercase; font-size: 10px; color: #718096; }
        table.data-table { width: 100%; border-collapse: collapse; margin-bottom: 30px; }
        table.data-table th { background-color: #f7fafc; border: 1px solid #cbd5e0; padding: 8px; text-align: left; font-size: 10px; text-transform: uppercase; color: #4a5568; }
        table.data-table td { border: 1px solid #cbd5e0; padding: 8px; font-size: 11px; }
        .text-center { text-align: center; }
        .text-right { text-align: right; }
        .badge { padding: 3px 6px; border-radius: 12px; font-size: 9px; font-weight: bold; text-transform: uppercase; }
        .footer { width: 100%; margin-top: 50px; page-break-inside: avoid; }
        .signature-box { width: 30%; display: inline-block; text-align: center; margin-top: 30px; }
        .signature-line { border-bottom: 1px solid #000; width: 80%; margin: 0 auto 5px auto; }
        .page-break { page-break-after: always; }
    </style>
</head>
<body>

    <div class="header">
        <h1>{{ strtoupper(\App\Models\Setting::getValue('company_name', 'PROFITIX HRM SYSTEM')) }}</h1>
        <p>Official Attendance & Performance Report ({{ ucfirst($type) }} Report)</p>
    </div>

    <table class="meta-info">
        <tr>
            <td width="50%">
                <div class="meta-title">Report Period:</div>
                <div style="font-size: 14px; font-weight: bold;">{{ \Carbon\Carbon::parse($dateFrom)->format('d M Y') }} to {{ \Carbon\Carbon::parse($dateTo)->format('d M Y') }}</div>
            </td>
            <td width="50%" class="text-right">
                <div class="meta-title">Generated On:</div>
                <div>{{ now()->format('d M Y, H:i') }}</div>
                <div class="meta-title" style="margin-top: 10px;">Generated By:</div>
                <div>{{ auth()->user()->name }} ({{ strtoupper(auth()->user()->role) }})</div>
            </td>
        </tr>
    </table>

    <table class="data-table">
        @if($type === 'daily' || $type === 'personal')
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Employee</th>
                    <th>Department</th>
                    <th>Check In</th>
                    <th>Check Out</th>
                    <th>Hours</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                @foreach($data as $r)
                <tr>
                    <td>{{ $r->summary_date->format('Y-m-d') }}</td>
                    <td>{{ $r->employee->full_name ?? '-' }}</td>
                    <td>{{ $r->employee->department->name ?? '-' }}</td>
                    <td>{{ $r->check_in_time ?? '-' }}</td>
                    <td>{{ $r->check_out_time ?? '-' }}</td>
                    <td class="text-center">{{ number_format($r->total_hours, 1) }}</td>
                    <td>{{ ucfirst(str_replace('_', ' ', $r->status)) }}</td>
                </tr>
                @endforeach
            </tbody>
        @elseif($type === 'department')
            <thead>
                <tr>
                    <th>Department</th>
                    <th>Employees</th>
                    <th>Present</th>
                    <th>Late</th>
                    <th>Absent</th>
                    <th>Leave</th>
                    <th>Holiday</th>
                    <th>Avg Hours</th>
                </tr>
            </thead>
            <tbody>
                @foreach($data as $r)
                <tr>
                    <td>{{ $r['department'] }}</td>
                    <td class="text-center">{{ $r['employees'] }}</td>
                    <td class="text-center">{{ $r['present'] }}</td>
                    <td class="text-center">{{ $r['late'] }}</td>
                    <td class="text-center">{{ $r['absent'] }}</td>
                    <td class="text-center">{{ $r['on_leave'] }}</td>
                    <td class="text-center">{{ $r['holiday'] }}</td>
                    <td class="text-center">{{ $r['avg_hours'] }}</td>
                </tr>
                @endforeach
            </tbody>
        @elseif($type === 'monthly')
            <thead>
                <tr>
                    <th>Employee</th>
                    <th>Code</th>
                    <th>Department</th>
                    <th>Days Present</th>
                    <th>Days Late</th>
                    <th>Absent</th>
                    <th>Leave</th>
                    <th>Holiday</th>
                    <th>Total Hours</th>
                    <th>Overtime</th>
                </tr>
            </thead>
            <tbody>
                @foreach($data as $r)
                <tr>
                    <td>{{ $r['employee'] }}</td>
                    <td>{{ $r['code'] }}</td>
                    <td>{{ $r['department'] }}</td>
                    <td class="text-center">{{ $r['present'] }}</td>
                    <td class="text-center">{{ $r['late'] }}</td>
                    <td class="text-center">{{ $r['absent'] }}</td>
                    <td class="text-center">{{ $r['on_leave'] }}</td>
                    <td class="text-center">{{ $r['holiday'] }}</td>
                    <td class="text-center font-bold">{{ $r['total_hours'] }}</td>
                    <td class="text-center">{{ $r['overtime'] }}</td>
                </tr>
                @endforeach
            </tbody>
        @endif
    </table>

    <div class="footer">
        <div class="signature-box">
            <div class="signature-line"></div>
            <div class="meta-title">Prepared By (HR)</div>
        </div>
        <div class="signature-box" style="float: right;">
            <div class="signature-line"></div>
            <div class="meta-title">Approved By (Manager)</div>
        </div>
        <div style="clear: both; margin-top: 40px; text-align: center; font-size: 9px; color: #a0aec0; text-transform: uppercase;">
            --- {{ \App\Models\Setting::getValue('company_name', 'Profitix HRM System') }} | Digitally Generated ---
        </div>
    </div>

</body>
</html>
